[package]
name = "design-tokens-theme-definitions"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints.rust]
unsafe_code = "deny"
missing_docs = "warn"

[dependencies]
catppuccin = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
toml = { workspace = true }
